typography_spectrum: 0.45873326784931123
color:
  brandStrength: 0.9838717402890325
  lightness: 0.328620690619573
  saturation: 0.16814321605488658
  rhythmicContrast: 0.5932571210432798
  brandColors:
    - '#B0CC99'
    - '#677E52'
    - '#B7CA79'
    - '#F6E8B1'
    - '#89725B'
layout_spectrum: 0.6272570940200239
name: The Trade Library
title: An Architect's Resource
description: everything on it's place
